POST http://localhost:9090/api/v1/segmentation
Accept: application/json
Content-Type: application/json

{
  "tag_id": "tag_1",
  "data": {
    "Level": 2,
    "GPS": 1,
    "UVS": 5
  }
}

###

PUT http://localhost:9090/api/v1/segmentation
Accept: application/json
Content-Type: application/json

{
  "tag_id": "tag_1",
  "expressions": [
    "GetRequest(\"http://localhost:9090/api/v1/status\") == 'OK'",
    "GetRequest(\"http://localhost:9090/api/v1/status\") == 'OK'",
    "Level > 1 && Level < 10 && GPS == 1 && UVS == 5",
    "GetRequest(\"http://localhost:9090/api/v1/statu\") == 257",
    "GetRequest(\"http://localhost:9090/api/v1/status\") == 256",
    "UVS == 5"
  ]
}

###
PUT http://localhost:9090/api/v1/status
Accept: application/json

###